
Quotes = new Array(
"There is no text more barbaric than the Old Testament of the Bible--books like Deuteronomy and Leviticus and Exodus. The Quran pales in comparison. -- Sam Harris, <a href='http://www.beliefnet.com/story/191/story_19107_1.html'>Beliefnet inverview</a>",
"The God of the Old Testament has got to be the most unpleasant character in all fiction: jealous, and proud of it, petty, vindictive, unjust, unforgiving, racist. -- Richard Dawkins, <a href='http://en.wikipedia.org/wiki/The_Root_of_All_Evil%3F'>The Root of All Evil?</a>",
"But you ask me what the scariest things are in Christianity: this infatuation with biblical prophecy and this notion that Jesus is going to come back as an avenging savior to kill all the bad people. -- Sam Harris, <a href='http://www.beliefnet.com/story/191/story_19107_1.html'>Beliefnet inverview</a>",
"The book, called the Bible, is filled with passages equally horrible, unjust and atrocious. This is the book to be read in schools in order to make our children loving, kind and gentle! This is the book they wish to be recognized in our Constitution as the source of all authority and justice! -- Robert Green Ingersoll, The Gods, (1872)",
"Whenever we read ... the cruel and tortuous executions, the unrelenting vindictiveness with which more than half the Bible is filled, it would be more consistent that we call it the word of a demon than the word of God. It is a history of wickedness that has served to corrupt and brutalize humankind. And, for my own part, I sincerely detest it, as I detest everything that is cruel. -- Thomas Paine, <a href='http://www.amazon.com/exec/obidos/ASIN/0879752734/skepticsannotate'>The Age of Reason</a>",
"Power-mad, belligerent, masochistic, petty, woefully insecure, extremely dangerous and unpredictable (and seemingly not too bright) Yahweh exhibits all the worst attributes of man. -- <a href='http://nontheistnexus.com/index.php?option=com_content&task=view&id=140&Itemid=295'>Brendan Powell Smith</a>, creator of the Brick Testament",
"Hell stands as a constant reminder of the essence of Christianity: God is to be obeyed because, in the final analysis, he is bigger and stronger than we are. And in addition, he is incomparably more vicious. -- George Smith, <a href='http://astore.amazon.com/skepticsannotate/detail/087975124X/103-3234597-0272641'>Atheism: The Case Against God</a>",
"If I had a child, the last book I would ever give to teach morality would be the Bible, especially the Old Testament. -- Bill Maher",
"Religion. It's given people hope in a world torn apart by religion. -- Jon Stewart",
"According to &#34Samuel,&#34 David took a census of the people. This excited the wrath of Jehovah, and as a punishment he allowed David to choose seven years of famine, a flight of three months from pursuing enemies, or three days of pestilence. David, having confidence in God, chose the three days of pestilence; and thereupon, God, the compassionate, on account of the sin of David, killed seventy thousand innocent men. Under the same circumstances, what would a devil have done? -- Robert Green Ingersoll, &#34About the Holy Bible&#34 (1894)"
);

var x = Math.floor (Quotes.length * Math.random());

document.write(Quotes[x]);