
Quotes = new Array(

//1 Nephi
"<span class='sci'>Yea, I make a record in the language of my father, which consists of the learning of the Jews and the language of the Egyptians.</span>--<a href='1ne/1.html#2'>1 Nephi 1:2</a>",
"<span class='v'>And it came to pass that I was constrained by the Spirit that I should kill Laban.</span>--<a href='1ne/4.html#10'>1 Nephi 4:10</a>",
"<span class='v'>And it came to pass that the Spirit said unto me again: Slay him.</span>--<a href='1ne/4.html#12'>1 Nephi 4:12</a>",
"<span class='v'>The Lord slayeth the wicked to bring forth his righteous purposes. It is better that one man should perish than that a nation should dwindle and perish in unbelief.</span>--<a href='1ne/4.html#13'>1 Nephi 4:13</a>",
"<span class='v'>Therefore I did obey the voice of the Spirit, and took Laban by the hair of the head, and I smote off his head with his own sword.</span>--<a href='1ne/4.html#18'>1 Nephi 4:18</a>",
"<span class='a'>The plates ... I have given the name of Nephi; wherefore, they are called the plates of Nephi, after mine own name; and these plates also are called the plates of Nephi.</span>--<a href='1ne/9.html#2'>1 Nephi 9:2</a>",
"<span class='i'>And it came to pass ... after they had dwindled in unbelief they became a dark, and loathsome, and a filthy people, full of idleness and all manner of abominations.</span>--<a href='1ne/12.html#23'>1 Nephi 12:23</a>",
"<span class='a'>And it came to pass</span> that I beheld this <span class='i'>great and abominable church; and I saw the devil that he was the founder of it.</span>--<a href='1ne/13.html#6'>1 Nephi 13:6</a>",
"<span class='i'>The Spirit of the Lord ... was upon the Gentiles, ... and I beheld that they were  white, and exceedingly fair and beautiful, like unto my people.</span>--<a href='1ne/13.html#15'>1 Nephi 13:15</a>",
"<span class='i'>The plain and most precious parts of the gospel of the Lamb ... have been kept back by that abominable church.</span>--<a href='1ne/13.html#32'>1 Nephi 13:32</a>",
"<span class='i'>That great and abominable church, which was founded by the devil and his children, that he might lead away the souls of men down to hell.</span>--<a href='1ne/14.html#3'>1 Nephi 14:3</a>",
"<span class='i'>Behold that great and abominable church, which is the mother of abominations, whose founder is the devil.</span>--<a href='1ne/14.html#9'>1 Nephi 14:9</a>",
"<span class='i'>There are save two churches only; the one is the church of the Lamb of God, and the other is the church of the devil</span>--<a href='1ne/14.html#10'>1 Nephi 14:10</a>",
"<span class='i'>Whoso belongeth not to the church of the Lamb of God belongeth to that great church, which is the mother of abominations; and she is the whore of all the earth.</span>--<a href='1ne/14.html#10'>1 Nephi 14:10</a>",
"<span class='i'>The wrath of God is poured out upon the mother of harlots, which is the great and abominable church of all the earth, whose founder is the devil.</span>--<a href='1ne/14.html#17'>1 Nephi 14:17</a>",
"<span class='a'>A round ball of curious workmanship; and it was of fine brass.  And within the ball were two spindles; and the one pointed the way whither we should go into the wilderness.</span>--<a href='1ne/16.html#10'>1 Nephi 16:10</a>",
"<span class='a'>We did follow the directions of the ball, which led us in the more fertile parts of the wilderness.</span>--<a href='1ne/16.html#16'>1 Nephi 16:16</a>",
"<span class='sci'>I did break my bow, which was made of fine steel.</span>--<a href='1ne/16.html#18'>1 Nephi 16:18</a>",
"<span class='a'>I will make thy food become sweet, that ye cook it not.</span>--<a href='1ne/17.html#12'>1 Nephi 17:12</a>",
"<span class='a'>He sent fiery flying serpents among them.</span>--<a href='1ne/17.html#41'>1 Nephi 17:41</a>",
"<span class='a'>Now I, Nephi, did not work the timbers after the manner which was learned by men, neither did I build the ship after the manner of men; but I did build it after the manner which the Lord had shown unto me; wherefore, it was not after the manner of men.</span>--<a href='1ne/18.html#2'>1 Nephi 18:2</a>",
"<span class='sci'>There were beasts in the forests of every kind, both the cow and the ox, and the ass and the horse, and the goat and the wild goat, and all manner of wild animals, which were for the use of men.</span>--<a href='1ne/18.html#25'>1 Nephi 18:25</a>",
"<span class='a'>I do not write anything upon plates save it be that I think it be sacred.  And now, if I do err, even did they err of old; not that I would excuse myself because of other men.</span>--<a href='1ne/19.html#6'>1 Nephi 19:6</a>",
"<span class='a'>And kings shall be thy nursing fathers.</span>--<a href='1ne/21.html#23'>1 Nephi 21:23</a>",
"<span class='v'>And I will feed them that oppress thee with their own flesh; they shall be drunken with their own blood as with sweet wine.</span>--<a href='1ne/21.html#26'>1 Nephi 21:26</a>",
"<span class='v'>And they shall be drunken with their own blood.</span>--<a href='1ne/22.html#13'>1 Nephi 22:13</a>",
"<span class='i'>A prophet shall the Lord your God raise up unto you, like unto me; him shall ye hear in all things whatsoever he shall say unto you.</span>--<a href='1ne/22.html#20'>1 Nephi 22:20</a>",


//2 Nephi
"<span class='a'>A choice seer will I raise up out of the fruit of thy loins; and he shall be esteemed highly among the fruit of thy loins.  And unto him will I give commandment that he shall do a work for the fruit of thy loins....</span>--<a href='2ne/3.html#7'>2 Nephi 3:7</a>",
"<span class='a'>Wherefore, the fruit of thy loins shall write; and the fruit of the loins of Judah shall write; and that which shall be written by the fruit of thy loins, and also that which shall be written by the fruit of the loins of Judah, shall grow together, ... establishing peace among the fruit of thy loins</span>....--<a href='2ne/3.html#12'>2 Nephi 3:12</a>",
"<span class='a'>And the Lord said unto me also: I will raise up unto the fruit of thy loins; and I will make for him a spokesman.  And I, behold, I will give unto him that he shall write the writing of the fruit of thy loins, unto the fruit of thy loins; and the spokesman of thy loins shall declare it.</span>--<a href='2ne/3.html#18'>2 Nephi 3:18</a>",
"<span class='i'>He had caused the cursing to come upon them ... wherefore, as they were white, and exceedingly fair and delightsome, that they might not be enticing unto my people the Lord God did cause a skin of blackness to come upon them.</span>--<a href='2ne/5.html#21'>2 Nephi 5:21</a>",
"<span class='i'>And cursed shall be the seed of him that mixeth with their seed; for they shall be cursed even with the same cursing.</span>--<a href='2ne/5.html#23'>2 Nephi 5:23</a>",
"<span class='i'>And because of their cursing which was upon them they did become an idle people, full of mischief and subtlety, and did seek in the wilderness for beasts of prey.</span>--<a href='2ne/5.html#24'>2 Nephi 5:24</a>",
"<span class='a'>And kings shall be thy nursing fathers.</span>--<a href='2ne/6.html#7'>2 Nephi 6:7</a>",
"<span class='i'>If ... they shall repent and fight not against Zion, and do not unite themselves to that great and abominable church, they shall be saved.</span>--<a href='2ne/6.html#12'>2 Nephi 6:12</a>",
"<span class='v'>They that believe not in him shall be destroyed, both by fire, and by tempest, and by earthquakes, and by bloodsheds, and by pestilence, and by famine.</span>--<a href='2ne/6.html#15'>2 Nephi 6:15</a>",
"<span class='v'>And I will feed them that oppress thee, with their own flesh; and they shall be drunken with their own blood as with sweet wine.</span>--<a href='2ne/6.html#18'>2 Nephi 6:18</a>",
"<span class='v'>Their torment is as a lake of fire and brimstone, whose flame ascendeth up forever and ever and has no end.</span>--<a href='2ne/9.html#16'>2 Nephi 9:16</a>",
"<span class='v'>Hell ... is endless torment.</span>--<a href='2ne/9.html#16'>2 Nephi 9:16, 26</a>",
"<span class='l'>They who are filthy shall be filthy still.</span>--<a href='2ne/9.html#16'>2 Nephi 9:16</a>",
"<span class='i'>If they will not repent and believe ... they must be damned.</span>--<a href='2ne/9.html#24'>2 Nephi 9:24</a>",
"<span class='i'>Many of our children shall perish in the flesh because of unbelief</span>--<a href='2ne/10.html#2'>2 Nephi 10:2</a>",
"<span class='i'>The Jews ... are the more wicked part of the world; and they shall crucify him ... there is none other nation on earth that would crucify their God.</span>--<a href='2ne/10.html#3'>2 Nephi 10:3</a>",
"<span class='a'>The kings of the Gentiles shall be nursing fathers.</span>--<a href='2ne/10.html#9'>2 Nephi 10:9</a>",
"<span class='i'>He that fighteth against Zion ... shall perish; for they are they who are the whore of all the earth.</span>--<a href='2ne/10.html#16'>2 Nephi 10:16</a>",
"<span class='a'>And now I, Nephi, write more of the words of Isaiah, for my soul delighteth in his words.</span>--<a href='2ne/11.html#2'>2 Nephi 11:2</a>",
"<span class='w'>The Lord will smite with a scab the crown of the head of the daughters of Zion, and the Lord will discover their secret parts.</span>--<a href='2ne/13.html#17'>2 Nephi 13:17</a>",
"<span class='a'>And it shall come to pass, instead of sweet smell there shall be stink.</span>--<a href='2ne/13.html#24'>2 Nephi 13:24</a>",
"<span class='p'>And in that day, seven women shall take hold of one man, saying ... let us be called by thy name to take away our reproach.</span>--<a href='2ne/14.html#1'>2 Nephi 14:1</a>",
"<span class='a'>And it shall come to pass ... that the Lord shall hiss for the fly ... and for the bee.</span>--<a href='2ne/17.html#18'>2 Nephi 17:18</a>",
"<span class='a'>The Lord shave with a razor ... the head, and the hair of the feet.</span>--<a href='2ne/17.html#20'>2 Nephi 17:20</a>",
"<span class='s'>I went unto the prophetess; and she conceived and bare a son.  Then said the Lord to me: Call his name, Maher-shalal-hash-baz.</span>--<a href='2ne/18.html#3'>2 Nephi 18:3</a>",
"<span class='v'>They shall eat every man the flesh of his own arm.</span>--<a href='2ne/19.html#20'>2 Nephi 19:20</a>",
"<span class='a'>With the breath of his lips shall he slay the wicked.</span>--<a href='2ne/21.html#4'>2 Nephi 21:4</a>",
"<span class='v'>Their children, also shall be dashed to pieces before their eyes ... and their wives ravished.</span>--<a href='2ne/23.html#16'>2 Nephi 23:16</a>",
"<span class='i'>Prepare slaughter for his children for the iniquities of their fathers</span>--<a href='2ne/24.html#21'>2 Nephi 24:21</a>",
"<span class='a'>Out of the serpent's root shall come forth a cockatrice, and his fruit shall be a fiery flying serpent.</span>--<a href='2ne/24.html#29'>2 Nephi 24:29</a>",
"<span class='i'>The Jews; for their works were works of darkness, and their doings were doings of abominations.</span>--<a href='2ne/25.html#2'>2 Nephi 25:2</a>",
"<span class='a'>My soul delighteth in the words of Isaiah.</span>--<a href='2ne/25.html#5'>2 Nephi 25:5</a>",
"<span class='a'>Wo unto them that fight against God and the people of his church.</span>--<a href='2ne/25.html#14'>2 Nephi 25:14</a>",
"<span class='a'>The Lord ... will proceed to do a marvelous work and a wonder.</span>--<a href='2ne/25.html#17'>2 Nephi 25:17</a>",
"<span class='a'>And behold the book shall be sealed.</span>--<a href='2ne/27.html#7'>2 Nephi 27:7</a>",
"<span class='a'>Wo be unto him that rejecteth the word of God!</span>--<a href='2ne/27.html#14'>2 Nephi 27:14</a>",
"<span class='a'>I will proceed to do a marvelous work among this people, yea, a marvelous work and a wonder.</span>--<a href='2ne/27.html#26'>2 Nephi 27:26</a>",
"<span class='a'>Yea, they are grasped with death, and hell; and death, and hell, and the devil.</span>--<a href='2ne/28.html#23'>2 Nephi 28:23</a>",
"<span class='a'>I shall proceed to do a marvelous work.</span>--<a href='2ne/29.html#1'>2 Nephi 29:1</a>",
"<span class='a'>The Gentiles shall say: A Bible! A Bible!  We have got a Bible, and there cannot be any more Bible.</span>--<a href='2ne/29.html#3'>2 Nephi 29:3</a>",
"<span class='a'>Thou fool, that shall say: A Bible, we have got a Bible, and we need no more Bible.</span>--<a href='2ne/29.html#6'>2 Nephi 29:6</a>",
"<span class='i'>Many generations shall not pass away among them, save they shall be a pure and delightsome people.</span>--<a href='2ne/30.html#6'>2 Nephi 30:6</a>",
"<span class='i'>And it shall come to pass that the Jews ... shall begin to believe in Christ and ... shall also become a delightsome people.</span>--<a href='2ne/30.html#7'>2 Nephi 30:7</a>",
"<span class='a'>With the breath of his lips shall he slay the wicked.</span>--<a href='2ne/30.html#9'>2 Nephi 30:9</a>",
"<span class='a'>No man will be angry at the words which I have written save he shall be of the spirit of the devil.</span>--<a href='2ne/33.html#5'>2 Nephi 33:5</a>",
"<span class='a'>If ye shall believe in Christ ye will believe in these words, for they are the words of Christ, and he hath given them unto me.</span>--<a href='2ne/33.html#10'>2 Nephi 33:10</a>",

//Jacob
"<span class='a'>And now it came to pass that the people of Nephi ... began to ... indulge themselves somewhat in wicked practices, such as like unto David of old desiring many wives and concubines.</span>--<a href='jacob/1.html#15'>Jacob 1:15</a>",
"<span class='g'>David and Solomon truly had many wives and concubines, which thing was abominable before me, saith the Lord.</span>--<a href='jacob/2.html#24'>Jacob 2:24</a>",
"<span class='g'>There shall not any man among you have save it be one wife; and concubines he shall have none;</span>--<a href='jacob/2.html#27'>Jacob 2:27</a>",
"<span class='w'>I, the Lord God, delight in the chastity of women.</span>--<a href='jacob/2.html#28'>Jacob 2:28</a>",
"<span class='i'>Unless ye shall repent of your sins that their skins will be whiter than yours.</span>--<a href='jacob/3.html#8'>Jacob 3:8</a>",
"<span class='i'>The darkness of their skins ... their filthiness came because of their fathers.</span>--<a href='jacob/3.html#9'>Jacob 3:9</a>",
"<span class='v'>Ye must go away into that lake of fire and brimstone, whose flames are unquenchable, and whose smoke ascendeth up forever and ever, which lake of fire and brimstone is endless torment.</span>--<a href='jacob/6.html#10'>Jacob 6:10</a>",

//Enos
"<span class='i'>The Lamanites ... were led by their evil nature that they became wild, and ferocious, and a bloodthirsty people, full of idolatry and filthiness.</span>--<a href='enos/1.html#20'>Enos 1:20</a>",
"<span class='i'>And many of them did eat nothing save it was raw meat; and they were continually seeking to destroy us.</span>--<a href='enos/1.html#20'>Enos 1:20</a>",

//Jarom
"<span class='i'>The Lamanites ... loved murder and would drink the blood of beasts.</span>--<a href='jarom/1.html#6'>6</a>",

//Omni
"<span class='a'>And he dwelt with them for the space of nine moons.</span>--<a href='omni/1.html#21'>1:21</a>",

//Mosiah
"<span class='a'>A seer is greater than a prophet.</span>--<a href='mosiah/8.html#15'>Mosiah 8:15</a>",
"<span class='a'>A seer is a revelator and a prophet also; and a gift which is greater can no man have.</span> -- <a href='mosiah/8.html#16'>Mosiah 8:16</a>",
"<span class='v'>God did hear our cries and did answer our prayers; and we did go forth in his might; yea, we did go forth against the Lamanites, and in one day and a night we did slay three thousand and forty-three.</span>--<a href='mosiah/9.html#18'>Mosiah 9:18</a>",
"<span class='i'>The Lamanites ... were a wild, and ferocious, and a blood-thirsty people.</span>--<a href='mosiah/10.html#11'>Mosiah 10:11-12</a>",
"<span class='v'>And it came to pass that we did drive them [the Lamanites] again out of our land; and we slew them with a great slaughter, even so many that we did not number them.</span>--<a href='mosiah/10.html#20'>Mosiah 10:20</a>",
"<span class='g'>He did not keep the commandments of God, but ... had many wives and concubines.</span>--<a href='mosiah/11.html#2'>Mosiah 11:2</a>",
"<span class='p'>Thus saith the Lord ... this generation ... shall be slain; and the vultures of the air, and the dogs, yea, and the wild beasts, shall devour their flesh.</span>--<a href='mosiah/12.html#2'>Mosiah 12:2</a>",
"<span class='i'>I will smite this my people with sore afflictions, yea, with famine and with pestilence; and I will cause that they shall howl all the day long.</span>--<a href='mosiah/12.html#4'>Mosiah 12:4</a>",
"<span class='a'>He shall be called the Son of God ... being the Father and the Son.</span>--<a href='mosiah/15.html#2'>Mosiah 15:2</a>",
"<span class='a'>All this was done in Mormon, yea, by the waters of Mormon, in the forest that was near the waters of Mormon; yea, the place of Mormon, the waters of Mormon, the forest of Mormon</span>--<a href='mosiah/18.html#30'>Mosiah 18:30</a>",
"<span class='g'>Every man should love his neighbor as himself.</span>--<a href='mosiah/23.html#15'>Mosiah 23:15</a>",
"<span class='g'>There should be an equality among all men.</span>--<a href='mosiah/27.html#3'>Mosiah 27:3</a>",
"<span class='g'>Every man should esteem his neighbor as himself.</span>--<a href='mosiah/27.html#4'>Mosiah 27:4</a>",
"<span class='a'>He translated them by the means of those two stones which were fastened into the two rims of a bow.</span>--<a href='mosiah/28.html#13'>Mosiah 28:13</a>",

//Alma
"<span class='i'>Those who did not belong to their church did indulge themselves in sorceries, and in idolatry or idleness, and in babblings, and in envyings and strife; wearing costly apparel; being lifted up in the pride of their own eyes; persecuting, lying, thieving, robbing, committing whoredoms, and murdering, and all manner of wickedness.</span>--<a href='alma/1.html#32'>Alma 1:32</a>",
"<span class='v'>The Lord did strengthen the hand of the Nephites, that they slew the Amlicites with great slaughter, ... and did slay them with much slaughter ... twelve thousand five hundred thirty and two souls.--<a href='alma/2.html#18'>Alma 2:18-19</a>",
"<span class='i'>And the skins of the Lamanites were dark, according to the mark which was set upon their fathers, which was a curse upon them.--<a href='alma/3.html#6'>Alma 3:6</a>",
"<span class='i'>And this was done that their seed might be distinguished from the seed of their brethren, that thereby the Lord God might preserve his people, that they might not mix and believe in incorrect traditions which would prove their destruction.</span>--<a href='alma/3.html#8'>Alma 3:8</a>",
"<span class='i'>And it came to pass that whosoever did mingle his seed with that of the Lamanites did bring the same curse upon his seed.</span>--<a href='alma/3.html#9'>Alma 3:9</a>",
"<span class='i'>Behold, the Lamanites have I cursed, and I will set a mark on them that they and their seed may be separated from thee and thy seed, from this time henceforth and forever.</span>--<a href='alma/3.html#14'>Alma 3:14</a>",
"<span class='i'>I will set a mark upon him that mingleth his seed with thy brethren, that they may be cursed also.</span>--<a href='alma/3.html#15'>Alma 3:15</a>",
"<span class='I'>If ye are not the sheep of the good shepherd ... the devil is your shepherd.</span>--<a href='alma/5.html#39'>Alma 5:39</a>",
"<span class='i'>I trust that ye are not in a state of so much unbelief....</span>--<a href='alma/7.html#6'>Alma 7:6</a>",
"<span class='a'>He shall be born of Mary, at Jerusalem.</span>--<a href='alma/7.html#10'>Alma 7:10</a>",
"<span class='a'>He who is filthy shall remain in his filthiness.</span>--<a href='alma/7.html#21'>Alma 7:21</a>",
"<span class='a'>Now the reckoning is thus -- a senine of gold, a seon of gold, a shum of gold, and a limnah of gold. A senum of silver, an amnor of silver, an ezrom of silver, and an onti of silver. </span>--<a href='alma/11.html#5'>Alma 11:5-6</a>",
"<span class='a'>Is the Son of God the very Eternal Father?   And Amulek said unto him: Yea, he is the very Eternal Father.</span>--<a href='alma/11.html#38'>Alma 11:38</a>",
"<span class='v'>Their torments shall be as a lake of fire and brimstone, whose flame ascendeth up forever and ever.</span>--<a href='alma/12.html#17'>Alma 12:17</a>",
"<span class='a'>And it came to pass in the eleventh year of the reign of the judges ... even until the fifth day of the second month in the eleventh year....</span>--<a href='alma/16.html#1'>Alma 16:1</a>",
"<span class='a'>Their dead bodies were heaped up upon the face of the earth, and they were covered with a shallow covering. And now so great was the scent thereof that the people did not go in to possess the land of Ammonihah for many years.</span>--<a href='alma/16.html#11'>Alma 16:11</a>",
"<span class='i'>The Lamanites [were] a wild and a hardened and a ferocious people; a people who delighted in murdering the Nephites, and robbing and plundering them ... that they might not labor for them with their own hands.</span>--<a href='alma/17.html#13'>Alma 17:13-14</a>",
"<span class='i'>Thus they were a very indolent people, many of whom did worship idols, and the curse of God had fallen upon them because of the traditions of their fathers.</span>--<a href='alma/17.html#15'>Alma 17:15</a>",
"<span class='v'>He [Ammon] smote off their arms with his sword; for he did withstand their blows by smiting their arms with the edge of his sword.</span>--<a href='alma/17.html#37'>Alma 17:37</a>",
"<span class='v'>And then went in unto the king, bearing the arms which had been smitten off by the sword of Ammon.</span>--<a href='alma/17.html#39'>Alma 17:39</a>",
"<span class='a'>Others say that he is dead and that he stinketh ... but as for myself, to me he doth not stink.</span>--<a href='alma/19.html#5'>Alma 19:5</a>",
"<span class='a'>And it came to pass that they called their names Anti-Nephi-Lehies; and they were called by this name and were no more called Lamanites.</span>--<a href='alma/23.html#17'>Alma 23:17</a>",
"<span class='i'>The Lamanites ... hearts delight in the shedding of blood; whose days have been spent in  the grossest iniquity.</span>--<a href='alma/26.html#24'>Alma 26:24</a>",
"<span class='v'>Tens of thousands of the Lamanites were slain and scattered abroad.</span>--<a href='alma/28.html#2'>Alma 28:2</a>",
"<span class='v'>And the bodies of many thousands are laid low in the earth, while the bodies of many thousands are moldering in heaps upon the face of the earth.</span>--<a href='alma/28.html#11'>Alma 28:11</a>",
"<span class='g'>Now there was no law against a man's belief; for it was strictly contrary to the commands of God that there should be a law which should bring men on to unequal grounds.</span>--<a href='alma/30.html#7'>Alma 30:7</a>",
"<span class='g'>If a man desired to serve God, it was his privilege; or rather, if he believed in God it was his privilege to serve him; but if he did not believe in him there was no law to punish him.</span>--<a href='alma/30.html#9'>Alma 30:9</a>",
"<span class='g'>There was a law that men should be judged according to their crimes. Nevertheless, there was no law against a man's belief; therefore, a man was punished only for the crimes which he had done; therefore all men were on equal grounds.</span>--<a href='alma/30.html#11'>Alma 30:11</a>",
"<span class='g'>It is the effect of a frenzied mind; and this derangement of your minds comes because of the traditions of your fathers, which lead you away into a belief of things which are not so.</span>--<a href='alma/30.html#16'>Alma 30:16</a>",
"<span class='g'>Ye say that those ancient prophecies are true.   Behold, I say that ye do not know that they are true.</span>--<a href='alma/30.html#22'>Alma 30:22</a>",
"<span class='g'>Ye say that this people is a guilty and a fallen people, because of the transgression of a  parent.  Behold, I say that a child is not guilty because of its parents.</span>--<a href='alma/30.html#25'>Alma 30:25</a>",
"<span class='g'>And ye also say that Christ shall come.  But behold, I say that ye do not know that there shall be a  Christ.</span>--<a href='alma/30.html#26'>Alma 30:26</a>",
"<span class='i'>God shall smite thee, that thou shalt become dumb, that thou shalt never open thy mouth any more, that thou shalt not deceive this people any more.</span>--<a href='alma/30.html#47'>Alma 30:47</a>",
"<span class='g'>We do not believe in the tradition of our brethren, which was handed down to them by the childishness of their fathers.</span>--<a href='alma/31.html#16'>Alma 31:16</a>",
"<span class='a'>If a man knoweth a thing he hath no cause to believe, for he knoweth it.</span>--<a href='alma/32.html#18'>Alma 32:18</a>",
"<span class='a'>The thing which our fathers call a ball, or director -- or our fathers called it Liahona, which is, being interpreted, a compass; and the Lord prepared it.</span>--<a href='alma/37.html#38'>Alma 37:38</a>",
"<span class='g'>Be filled with love.</span>--<a href='alma/38.html#12'>Alma 38:12</a>",
"<span class='i'>The Amalekites were of a more wicked and murderous disposition than the Lamanites.</span>--<a href='alma/43.html#6'>Alma 43:6</a>",
"<span class='i'>The Lord is with us; and ye behold that he has delivered you into our hands.</span>--<a href='alma/44.html#3'>Alma 44:3</a>",
"<span class='i'>God ... has strengthened  our arms that we have gained power over you, by  our faith, by our religion, and by our rites of worship, and by  our church.</span>--<a href='alma/44.html#5'>Alma 44:5</a>",
"<span class='i'>Moroni was angry, because of the stubbornness of the Lamanites; therefore he commanded  his people that they should fall upon them and slay them.</span>--<a href='alma/44.html#17'>Alma 44:17</a>",
"<span class='i'>Whomsoever of the Amalickiahites that would not enter into a covenant to support the cause of freedom, that they might maintain a free government, he caused to be put to death.</span>--<a href='alma/46.html#35'>Alma 46:35</a>",
"<span class='i'>These dissenters ... became ... more wild, wicked and ferocious than the Lamanites.</span>--<a href='alma/47.html#36'>Alma 47:36</a>",
"<span class='a'>God would prosper them in the land, or in other words ... God ... would prosper them in the land.</span>--<a href='alma/48.html#15'>Alma 48:15</a>",
"<span class='i'>Thousands of their wicked brethren have been consigned to bondage, or to perish by the sword, or to dwindle in unbelief, and mingle with the Lamanites.</span>--<a href='alma/50.html#22'>Alma 50:22</a>",
"<span class='v'>There were four thousand of those dissenters who were hewn down by the sword.</span>--<a href='alma/51.html#19'>Alma 51:19</a>",
"<span class='i'>The remainder of those dissenters, rather than be smitten down to the earth by the sword, yielded to the standard of liberty, and were compelled to hoist the title of liberty.</span>--<a href='alma/51.html#20'>Alma 51:20</a>",
"<span class='g'>And as concerning that God whom ye say we have rejected, behold, we know not such a being; neither do ye.</span>--<a href='alma/54.html#21'>Alma 54:21</a>",
"<span class='v'>We did slay upwards of two thousand of them after they had surrendered themselves prisoners of war.</span>--<a href='alma/57.html#14'>Alma 57:14</a>",
"<span class='i'>Whosoever was found denying their freedom was speedily executed according to the law.</span>--<a href='alma/62.html#10'>Alma 62:10</a>",

// Helaman
"<span class='i'>They had  become a wicked people, insomuch that they were wicked even like unto the Lamanites.</span> -- <a href='hel/4.html#22'>Helaman 4:22</a>",
"<span class='i'>They began to disbelieve  in the spirit of prophecy and in the spirit of revelation; and the judgments of God did stare them in the face.</span> -- <a href='hel/4.html#23'>Helaman 4:23</a>",
"<span class='i'>Therefore the Lord did cease to preserve them by his miraculous and matchless  power, for they had fallen into a state of unbelief.</span> -- <a href='hel/4.html#25'>Helaman 4:25</a>",
"<span class='i'>There is no other way nor means whereby man can be saved, only through the atoning blood of Jesus Christ.</span> -- <a href='hel/5.html#9'>Helaman 5:9</a>",
"<span class='a'>Nephi and Lehi were ... standing in the midst of fire and were not burned.</span> -- <a href='hel/5.html#23'>Helaman 5:23</a>",
"<span class='a'>And it came to pass that there came a voice as if it were above the cloud of darkness, saying ... </span> -- <a href='hel/5.html#29'>Helaman 5:29:</a>",
"<span class='a'>And also again the third time the voice came, and did speak unto them marvelous words which cannot be uttered by man; and the walls did tremble again, and the earth shook as if it were about to divide asunder.</span> -- <a href='hel/5.html#33'>Helaman 5:33</a>",
"<span class='a'>The faces of Nephi and Lehi; and behold, they did shine exceedingly, even as the faces of angels.</span> -- <a href='hel/5.html#36'>Helaman 5:36</a>",
"<span class='i'>There were many of the Nephites who had become hardened and impenitent and grossly wicked, insomuch that they did reject the word of God and all the preaching and prophesying.</span> -- <a href='hel/6.html#2'>Helaman 6:2</a>",
"<span class='v'>Behold, thou art Nephi, and I am God.  Behold, I declare it unto thee in the presence of mine angels, that ye shall have power over this people, and shall smite the earth with famine, and with pestilence, and destruction.</span> -- <a href='hel/10.html#6'>Helaman 10:6</a>",
"<span class='i'>If ye shall say that God shall smite this people, it shall come to pass.</span>. -- <a href='hel/10.html#10'>Helaman 10:10</a>",
"<span class='v'>Except the Lord doth chasten his people with many afflictions, yea, except he doth visit them with death and with terror, and with famine and with all manner of pestilence, they will not remember him.</span> -- <a href='hel/12.html#3'>Helaman 12:3</a>",
"<span class='p'>And four hundred years shall not pass away before I will cause that they shall be smitten; yea, I will visit them with the sword and with famine and with pestilence.</span> -- <a href='hel/13.html#9'>Helaman 13:9</a>",
"<span class='v'>If it were not for the righteous who are in this great city, behold, I would cause that fire should come down out of heaven and destroy it.</span> -- <a href='hel/13.html#13'>Helaman 13:13</a>",
"<span class='a'>Behold, we are surrounded by demons.</span> -- <a href='hel/13.html#37'>Helaman 13:37</a>",
"<span class='a'>Jesus Christ, the Son of God, the Father of heaven and of earth....</span> -- <a href='hel/14.html#12'>Helaman 14:12</a>",
"<span class='i'>But behold my brethren, the Lamanites hath he hated ... because of the iniquity of the tradition of their fathers.</span> -- <a href='hel/15.html#4'>Helaman 15:4</a>",
"<span class='i'>If they will not repent, and observe to do my will, I will utterly destroy them, saith the Lord, because of their unbelief.</span> -- <a href='hel/15.html#17'>Helaman 15:17</a>",

//3 Nephi

"<span class='a'>Now it came to pass that there was a day set apart by the unbelievers, that all those who believed in those traditions should be put to death.</span>--<a href='3ne/1.html#9'>3 Nephi 1:9</a>",
"<span class='a'>Behold, at the going down of the sun there was no darkness.</span>--<a href='3ne/1.html#15'>3 Nephi 1:15</a>",
"<span class='a'>It came to pass that there was no darkness in all that night, but it was as light as though it was mid-day.</span>--<a href='3ne/1.html#19'>3 Nephi 1:19</a>",
"<span class='i'>And their curse was taken from them, and their skin became white like unto the Nephites.</span>--<a href='3ne/2.html#15'>3 Nephi 2:15</a>",
"<span class='i'>And their young men and their daughters became exceedingly fair, and they were numbered among the Nephites.</span>--<a href='3ne/2.html#16'>3 Nephi 2:16</a>",
"<span class='a'>And now behold, there was not a living soul among all the people of the Nephites who did doubt in the least the words of all the holy prophets who had spoken.</span>--<a href='3ne/5.html#1'>3 Nephi 5:1</a>",
"<span class='a'>And thus had the twenty and second year passed away, and the twenty and third year also, and the twenty and fourth, and the twenty and fifth; and thus had twenty and five years passed away.</span>--<a href='3ne/5.html#7'>3 Nephi 5:7</a>",
"<span class='a'>There was not any light seen, neither fire, nor glimmer, neither the sun, nor the moon, nor the stars.</span>--<a href='3ne/8.html#22'>3 Nephi 8:22</a>",
"<span class='a'>It came to pass that there was a voice heard among all the inhabitants of the earth, upon all the face of this land, crying ... </span>--<a href='3ne/9.html#1'>3 Nephi 9:1</a>",
"<span class='a'>Behold, I am Jesus Christ the Son of God.</span>--<a href='3ne/9.html#15'>3 Nephi 9:15</a>",
"<span class='a'>It came to pass that there came a voice again unto the people, and all the people did hear, and did witness of it, saying ...</span>--<a href='3ne/10.html#3'>3 Nephi 10:3</a>",
"<span class='a'>It came to pass that ... they heard a voice as if it came out of heaven.</span>--<a href='3ne/11.html#3'>3 Nephi 11:3</a>",
"<span class='a'>He that hath the spirit of contention is not of me, but is of the devil.</span>--<a href='3ne/11.html#29'>3 Nephi 11:29</a>",
"<span class='v'>Whoso believeth not in me, and is not baptized, shall be damned. </span>--<a href='3ne/11.html#34'>3 Nephi 11:34</a>",
"<span class='i'>They were as white as the countenance and also the garments of Jesus; and behold the whiteness thereof did exceed all the whiteness, yea, even there could be nothing upon earth so white as the whiteness thereof.</span>--<a href='3ne/19.html#25'>3 Nephi 19:25</a>",
"<span class='i'>Behold  they were white, even as Jesus.</span>--<a href='3ne/19.html#30'>3 Nephi 19:20</a>",
"<span class='v'>Ye shall be among them as a ... young lion among the flocks of sheep, who, if he goeth through both treadeth down and teareth in pieces.</span>--<a href='3ne/20.html#16'>3 Nephi 20:16</a>",
"<span class='i'>Whosoever will not believe ... shall be cut off.</span>--<a href='3ne/21.html#11'>3 Nephi 21:11</a>",
"<span class='p'>Other scriptures I would that ye should write, that ye have not.</span>--<a href='3ne/23.html#6'>3 Nephi 23:6</a>",

//4 Nephi
"<span class='a'>And thus did the thirty and eighth year pass away, and also the thirty and ninth, and forty and first, and the forty and second, yea, even until forty and nine years had passed away, and also the fifty and first, and the fifty and second; yea, and even until fifty and nine years had passed away.</span>--<a href='4ne/1.html#6'>4 Nephi 6</a>",
"<span class='i'>The people of Nephi did wax strong, and did multiply exceedingly fast, and became an exceedingly fair and delightsome people.</span>--<a href='4ne/1.html#10'>4 Nephi 10</a>",
"<span class='a'>And it came to pass that the seventy and first year passed away, and also the seventy and second year, yea, and in fine, till the seventy and ninth year had passed away; yea, even an hundred years had passed away.</span>--<a href='4ne/1.html#14'>4 Nephi 14</a>",

//Mormon
"<span class='v'>I saw thousands of them hewn down in open rebellion against their God, and heaped up as dung upon the face of the land.</span>--<a href='mormon/2.html#15'>Mormon 2:15</a>",
"<span class='int'>This people ... shall become a dark, a filthy, and a loathsome people ... because of their unbelief and idolatry.</span>--<a href='mormon/5.html#15'>Mormon 5:15</a>",
"<span class='int'>They were once a delightsome people ... But now, behold, they are led about by Satan.</span>--<a href='mormon/5.html#17'>Mormon 5:17-18</a>",
"<span class='v'>Repent ... lest a remnant of the seed of Jacob shall go forth among you as a lion, and tear you in pieces.</span>--<a href='mormon/5.html#24'>Mormon 5:24</a>",
"<span class='a'>If ye believe that ye will believe this also.</span>--<a href='mormon/7.html#9'>Mormon 7:9</a>",
"<span class='a'>If there be faults they be the faults of a man.  But behold, we know no fault.</span>--<a href='mormon/8.html#17'>Mormon 8:17</a>",
"<span class='v'>He that condemneth, let him be aware lest he shall be in danger of hell fire.</span>--<a href='mormon/8.html#17'>Mormon 8:17</a>",
"<span class='v'>He that shall breathe out wrath and strifes against the work of the Lord ... the same is in danger to be hewn down and cast into the fire.</span>--<a href='mormon/8.html#21'>Mormon 8:21</a>",
"<span class='a'>Behold, the Lord hath shown unto me great and marvelous things concerning that which must shortly come.</span>--<a href='mormon/8.html#34'>Mormon 8:34</a>",
"<span class='int'>O then ye unbelieving, turn ye unto the Lord ... that perhaps ye may be found spotless, pure, fair, and white.</span>--<a href='mormon/9.html#6'>Mormon 9:6</a>",
"<span class='a'>The reason why he ceaseth to do miracles among the children of men is because that they dwindle in unbelief.</span>--<a href='mormon/9.html#20'>Mormon 9:20</a>",
"<span class='a'>We have written this record in ... reformed Egyptian.... If our plates had been sufficiently large we should have written in Hebrew.</span>--<a href='mormon/9.html#32'>Mormon 9:32-33</a>",
"<span class='a'>Because that none other people knoweth our language, therefore he hath prepared means for the interpretation thereof.</span>--<a href='mormon/9.html#34'>Mormon 9:34</a>"


);

var x = Math.floor (Quotes.length * Math.random());

document.write(Quotes[x]);